export type Source = {url: string; title: string};
export type Participant = {id: string; name: string; phone: string; email: string; source_row: number};
export type Company = {id: string; original_name: string; name: string; niche: string; website: string; actual_city: string; actual_neighborhood: string; aliases: string[]; status: string; notes: string; sources: Source[]; participants: Participant[]; record_type: string; activity: string};
export type Result = Company & {appearances: number; uncertain: number; validQueries: number; plannedQueries: number; bestPosition: number | null; positions: number[]; competitors: {name: string; count: number}[]};
export type Task = {id: string; company_id?: string; niche: string; iteration: number; status: string; stage: string; error: string; identity_mode?: string; company_name?: string; company_city?: string; company_neighborhood?: string; errorCode?: string; created_at: string; updated_at: string};
export type Diagnostic = {at: string; stage: string; event: string; retryAt?: string; retryNumber?: number; delaySeconds?: number; model: string; code?: string; message?: string; status?: string; incompleteReason?: string; budget?: number; effort?: string; usage?: unknown; responseId?: string; partialText?: string};
export type Detail = Task & {diagnostics: Diagnostic[]; extractionModel: string; searchModel: string; prompt: string; model: string; kind: string; raw: {text?: string; sources?: Source[]; annotations?: {start: number; end: number; url: string; title: string}[]; collectedAt?: string}; result: {mentions?: {name: string; position: number | null}[]; niche?: string; city?: string; neighborhood?: string; reason?: string}};
export type NicheOutcome = "pending" | "accepted" | "unchanged" | "reused" | "inconclusive" | "failed" | "superseded" | "stopped" | "queued" | "running";
export type NicheResult = {id: string; companyId: string; name: string; previousNiche: string; currentNiche: string; proposedNiche: string; approvedNiche: string; city: string; neighborhood: string; reason: string; origin: string; outcome: NicheOutcome; suggestionId: string; suggestionStatus: string; hasSources: boolean; autoApproved: boolean; verification: string; verificationReason: string};
export type Identification = {counts: Record<NicheOutcome | "changed" | "autoApproved", number>; rows: NicheResult[]; legacyResults: number};
export type Job = {id: string; kind: string; status: string; model: string; extraction_model: string; pause_reason: string; waiting?: number; failureSummary: {code: string; label: string; count: number}[]; repetitions: number; query_template: string; created_at: string; total: number; completed: number; failed: number; tasks: Task[]; results?: Result[]; identification?: Identification};
export type Immersion = {id: string; name: string; city: string; region: string; event_date: string; filename: string; company_count: number; participant_count: number};
export type Settings = {identificationModel: string; model: string; extractionModel: string; keyConfigured: boolean; keyHint: string; fromEnvironment: boolean; googleMapsConfigured: boolean};

export type GoogleProfile = {lat?: number | null; lng?: number | null; status: "matched" | "not_found" | "ambiguous" | "resolving" | "pending" | "error" | "not_configured"; placeId?: string; name?: string; address?: string; rating?: number | null; reviewCount?: number; mapsUrl?: string; website?: string; primaryType?: string; businessStatus?: string; checkedAt?: string; attribution?: string; confidence?: number; reason?: string};
export type GoogleProfilesResponse = {configured: boolean; attribution: string; profiles: Record<string, GoogleProfile>};
export type NicheSuggestion = {id: string; companyId: string; jobId: string; status: string; origin: string; createdAt: string; name: string; niche: string; city: string; neighborhood: string; currentNiche: string; currentCity: string; currentNeighborhood: string; canAcceptInBatch: boolean; reason: string; sources: Source[]};
export type State = {version: string; settings: Settings; immersions: Immersion[]; selectedId: string; companies: Company[]; jobs: Job[]; nicheSuggestions: NicheSuggestion[]};
export type Sheet = {name: string; rows: number; preview: string[][]; columns: number; hasHeader: boolean; mapping: Record<string, number>};
export type Staged = {uploadId: string; filename: string; sheets: Sheet[]};

export type Preparation = {reused?: boolean; id: string; status: string; model: string; completedBatches: number; totalBatches: number; error: string; mapping: Record<string, number>; rows: {line: number; person: string; company: string; activity: string; niche: string; needsReview: boolean}[]; diagnostics: unknown[]};

export type DashboardFilters = {q: string; niche: string; city: string; neighborhood: string; company: string; presence: string; position: string};
export type DashboardCompany = {companyId: string; name: string; niche: string; city: string; neighborhood: string; website: string; appearances: number; uncertain: number; validQueries: number; plannedQueries: number; frequency: number; frequencyPercent: number; presenceLabel: string; bestRank: number | null; averageRank: number | null; medianRank: number | null; worstRank: number | null; top1: number; top3: number; averageMentionOrder: number | null; competitors: {name: string; count: number}[]};
export type DashboardEntity = {entityKey: string; name: string; website: string; matchedCompanyId: string; matchStatus: string; citations: number; queries: number; top1: number; top3: number; averageRank: number | null; bestRank: number | null; averageMentionOrder: number | null; niches: string[]; cities: string[]; neighborhoods: string[]; asCompetitor: number; asTarget: number; entityType: "audited" | "competitor"};
export type DashboardSummary = {generatedAt: string; job: {id: string; status: string; model: string; createdAt: string; repetitions: number; queryTemplate: string}; filters: DashboardFilters; options: {niches: string[]; cities: string[]; neighborhoods: string[]; companies: {id: string; name: string}[]}; kpis: {auditedCompanies: number; recommendedCompanies: number; recommendationRate: number; competitorsUnique: number; queriesPlanned: number; queriesValid: number; citations: number; top1Companies: number; googleMatched: number; googleTotal: number; niches: number; cities: number; neighborhoods: number}; quality: {total: number; completed: number; valid: number; failed: number; incomplete: number; successRate: number}; alerts: {type: string; count: number; label: string; filter: string}[]; companies: DashboardCompany[]; entityRanking: DashboardEntity[]; nicheRankings: {niche: string; entities: {entityKey: string; name: string; citations: number}[]}[]; groupRankings: {niche: {label: string; entities: {entityKey: string; name: string; citations: number}[]}[]; city: {label: string; entities: {entityKey: string; name: string; citations: number}[]}[]; neighborhood: {label: string; entities: {entityKey: string; name: string; citations: number}[]}[]}; positionDistribution: {position: number | null; count: number}[]};
export type DashboardAuditRow = {taskId: string; companyId: string; company: string; niche: string; city: string; neighborhood: string; iteration: number; status: string; evaluable: boolean; targetStatus: string; explicitRank: number | null; mentionOrder: number | null; prompt: string; mentions: {entityKey: string; name: string; explicitRank: number | null; mentionOrder: number; matchedCompanyId: string; matchStatus: string}[]; error: string; createdAt: string; updatedAt: string};
export type DashboardAudit = {page: number; pageSize: number; total: number; pages: number; rows: DashboardAuditRow[]; filters: DashboardFilters};
export type DashboardMapPin = {entityKey: string; name: string; entityType: "audited" | "competitor"; matchedCompanyId: string; lat: number; lng: number; citations: number; top1: number; averageRank: number | null; niche: string; city: string; neighborhood: string; rating: number | null; reviewCount: number; mapsUrl: string; address: string; businessStatus: string};
export type DashboardMap = {configured: boolean; attribution: string; pins: DashboardMapPin[]; eligible: number; located: number; limit: number};
export type DashboardEntityDetail = {entityKey: string; name: string; website: string; matchedCompanyId: string; matchStatus: string; citations: number; queries: number; bestRank: number | null; averageRank: number | null; top1: number; top3: number; niches: string[]; cities: string[]; neighborhoods: string[]; cooccurring: {entityKey: string; name: string; count: number}[]; occurrences: {taskId: string; targetCompany: string; targetCompanyId: string; niche: string; city: string; neighborhood: string; explicitRank: number | null; mentionOrder: number; createdAt: string}[]};
